# Generated by Django 3.0.5 on 2020-06-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
