# Generated by Django 3.0.5 on 2020-06-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0004_auto_20200627_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(default='brak', upload_to=''),
            preserve_default=False,
        ),
    ]
