# Generated by Django 3.0.5 on 2020-07-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0008_auto_20200628_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_To_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_to_question', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pytania.Question')),
            ],
        ),
    ]
