# Generated by Django 3.0.5 on 2020-07-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0011_auto_20200718_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text_To_Question',
        ),
    ]
