# Generated by Django 3.0.5 on 2020-07-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0013_text_to_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_to_question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='text_question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pytania.Text_To_Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text_to_question',
            name='text_to_question',
            field=models.TextField(default=''),
        ),
    ]
