# Generated by Django 3.0.5 on 2020-07-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0014_auto_20200718_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_to_question',
            name='text_to_question',
            field=models.TextField(),
        ),
    ]
