# Generated by Django 3.0.5 on 2020-07-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0015_auto_20200718_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pytania.Text_To_Question'),
        ),
    ]
