# Generated by Django 3.0.5 on 2020-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0017_question_type_of_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_of_answers',
            field=models.CharField(blank=True, choices=[('true_false', 'true_false'), ('a_b_c', 'a_b_c'), ('1_2_3', '1_2_3'), ('author_book', 'author_book'), ('letter_to_number', 'letter_to_number')], default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
