# Generated by Django 3.0.5 on 2020-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0018_auto_20200719_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_of_answers',
            field=models.CharField(choices=[('true_false', 'true_false'), ('a_b_c', 'a_b_c'), ('1_2_3', '1_2_3'), ('author_book', 'author_book'), ('letter_to_number', 'letter_to_number')], max_length=50),
        ),
    ]
