# Generated by Django 3.0.5 on 2020-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0019_auto_20200719_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.CharField(choices=[('matura', 'matura'), ('zawodowy', 'zawodowy')], max_length=50),
        ),
    ]
