# Generated by Django 3.0.5 on 2020-07-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0022_auto_20200724_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=400),
        ),
    ]
