# Generated by Django 3.0.5 on 2020-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0027_auto_20200727_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
