# Generated by Django 3.0.5 on 2021-07-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0028_question_example_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='wrong_answer1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='wrong_answer2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='wrong_answer3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
